// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function FindFiles(arg1) {
  return window['go']['main']['App']['FindFiles'](arg1);
}

export function FindInFiles(arg1) {
  return window['go']['main']['App']['FindInFiles'](arg1);
}

export function FindSymbols(arg1) {
  return window['go']['main']['App']['FindSymbols'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function UpdateSession(arg1, arg2) {
  return window['go']['main']['App']['UpdateSession'](arg1, arg2);
}
