// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateSession(arg1:string):Promise<models.Session>;

export function DeleteSession(arg1:string):Promise<void>;

export function FindFiles(arg1:string):Promise<Array<string>>;

export function FindInFiles(arg1:string):Promise<Array<models.SearchResult>>;

export function FindSymbols(arg1:string):Promise<Array<models.Symbol>>;

export function GetConfig():Promise<models.ServerConfig>;

export function GetMessages(arg1:string):Promise<Array<models.MessageWithParts>>;

export function GetSession(arg1:string):Promise<models.Session>;

export function GetSessions():Promise<Array<models.Session>>;

export function ReadFile(arg1:string):Promise<models.FileContent>;

export function SendMessage(arg1:string,arg2:models.ChatInput):Promise<models.MessageWithParts>;

export function UpdateSession(arg1:string,arg2:string):Promise<models.Session>;
