// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CompactSession(arg1:string):Promise<void>;

export function CreateSession(arg1:string):Promise<models.Session>;

export function DeleteSession(arg1:string):Promise<void>;

export function FindFiles(arg1:string):Promise<Array<string>>;

export function FindInFiles(arg1:string):Promise<Array<models.SearchResult>>;

export function FindSymbols(arg1:string):Promise<Array<models.Symbol>>;

export function GetAgents():Promise<Array<models.Agent>>;

export function GetAppConfig():Promise<models.AppConfig>;

export function GetConfig():Promise<models.ServerConfig>;

export function GetMessages(arg1:string):Promise<Array<models.MessageWithParts>>;

export function GetProviders():Promise<models.ProvidersResponse>;

export function GetSession(arg1:string):Promise<models.Session>;

export function GetSessionTokens(arg1:string):Promise<models.SessionTokens>;

export function GetSessions():Promise<Array<models.Session>>;

export function PolishText(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<models.FileContent>;

export function SendMessage(arg1:string,arg2:models.ChatInput):Promise<models.MessageWithParts>;

export function StopMessage(arg1:string):Promise<void>;

export function SummarizeSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateAppConfig(arg1:models.AppConfig):Promise<void>;

export function UpdateSession(arg1:string,arg2:string):Promise<models.Session>;
